wutsi:
  asset-url: https://${wutsi.storage.s3.bucket}.s3.amazonaws.com/static/wutsi-blog-web
  domain: int-com-wutsi-blog-web.herokuapp.com
  base-url: https://${wutsi.domain}

  backend:
    base-url: https://int-com-wutsi-blog.herokuapp.com
    track-url: https://int-com-wutsi-track.herokuapp.com

  oauth:
    github:
      client-id: "43bf80531cd351c84f5b"
  pwa:
    manifest:
      name: "Wutsi - Int"

  storage:
    s3:
      bucket: "int-wutsi"

  toggles:
    channel: true
    channel-twitter: true
    channel-facebook: true
    channel-linkedin: true
    pwa-push-notification: false
    sso-facebook: true
    sso-google: true
    sso-github: true
    sso-twitter: true
    sso-linkedin: false
    sso-yahoo: true

  rabbitmq:
    enabled: true
  security:
    api-key:
      id: ${API_KEY_ID}
