wutsi:
  asset-url: https://int-wutsi.s3.amazonaws.com/static/wutsi-blog-web
  domain: www.wutsi.com
  base-url: https://${wutsi.domain}

  backend:
    baseurl: https://com-wutsi-blog.herokuapp.com

  oauth:
      facebook:
        client-id: "466330503408293"
      github:
        client-id: "900cfd0accedc133ea5b"
      google:
        client-id: "28035834807-789vmmloq8u12nvvp4ki2bbcqsqvskf0.apps.googleusercontent.com"

  toggles:
    sso-facebook: true
    sso-google: true
    sso-twitter: false
    sso-github: false
    qa-login: false

  google:
    ga:
      code: "UA-120456146-1"

  storage:
    s3:
      bucket: "prod-wutsi"
