wutsi:
  asset-url: https://int-wutsi.s3.amazonaws.com/static/wutsi-blog-web
  domain: int-com-wutsi-blog-web.herokuapp.com
  base-url: https://${wutsi.domain}

  backend:
    baseurl: https://int-com-wutsi-blog.herokuapp.com

  oauth:
      github:
        client-id: 43bf80531cd351c84f5b
        client-secret: 986634ef3a7c8ac6e66f9a75f5b0a1c4dec68918
      facebook:
        client-id: 629340480740249
      google:
        client-id: 806985813772-ae9dav3ankkfcpbq0optkkv7ve6g0q5c.apps.googleusercontent.com
        client-secret: ySK8Wohv1go1xA7GPbwJG685

  storage:
    s3:
      region: "us-east-1"
      bucket: "int-wutsi-blog"
    servlet:
      hostname: "int-com-wutsi-blog.herokuapp.com"

  toggles:
    sso-facebook: true
    sso-google: true
    sso-twitter: false
    sso-github: true
