wutsi:
  asset-url: https://${wutsi.storage.s3.bucket}.s3.amazonaws.com/static/wutsi-blog-web
  domain: int-com-wutsi-blog-web.herokuapp.com
  base-url: https://${wutsi.domain}

  backend:
    baseurl: https://int-com-wutsi-blog.herokuapp.com

  oauth:
      github:
        client-id: "43bf80531cd351c84f5b"
      facebook:
        client-id: "629340480740249"
      google:
        client-id: "255903690741-okpg7c4dje7764qgs2mtetjr48ipshpe.apps.googleusercontent.com"

  pwa:
    manifest:
      name: "Wutsi - Int"

  storage:
    s3:
      bucket: "int-wutsi"

  toggles:
    sso-facebook: true
    sso-google: true
    sso-github: true
