twitter:
  consumer-key: "000000"
  consumer-secret: "0000000"

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

  security:
    basic:
      enabled: false

  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 10240KB

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
    min-response-size: 512

logging:
  level:
    root: INFO
    com.wutsi: DEBUG
    org.springframework: INFO

  pattern:
    console: "%d Type=%level Logger=%c Thread=%thread %m%n"
    file: "%d Type=%level Logger=%c Thread=%thread %m%n"

wutsi:
  asset-url: ""
  domain: localhost
  base-url: "http://${wutsi.domain}:8081"

  aws:
    s3:
      region: "us-east-1"

  backend:
    base-url: http://localhost:8080
    authentication:
      endpoint: ${wutsi.backend.base-url}/v1/auth
    channel:
      endpoint: ${wutsi.backend.base-url}/v1/channel
    comment:
      endpoint: ${wutsi.backend.base-url}/v1/comment
    contract:
      endpoint: ${wutsi.backend.base-url}/v1/contract
    earning:
      endpoint: ${wutsi.backend.base-url}/v1/earning
    mail:
      endpoint: ${wutsi.backend.base-url}/v1/mail
    partner:
      endpoint: ${wutsi.backend.base-url}/v1/partner
    push_subscription:
      endpoint: ${wutsi.backend.base-url}/v1/push/subscription
    recommendation:
      endpoint: ${wutsi.backend.base-url}/v1/recommendation
    sort:
      endpoint: ${wutsi.backend.base-url}/v1/sort
    story:
      endpoint: ${wutsi.backend.base-url}/v1/story
    stats:
      endpoint: ${wutsi.backend.base-url}/v1/stats
    tag:
      endpoint: ${wutsi.backend.base-url}/v1/tag
    topic:
      endpoint: ${wutsi.backend.base-url}/v1/topic
    track:
      endpoint: ${wutsi.backend.base-url}/v1/track
    user:
      endpoint: ${wutsi.backend.base-url}/v1/user
    view:
      endpoint: ${wutsi.backend.base-url}/v1/view

  cache:
    story-ttl-seconds: 1800    # 30min

  facebook:
    pixel:
      code:

  google:
    ga:
      code:

  http:
    client-id: wutsi-blog-web

  image-kit:   # Configuration of integration with imagekit.io
    origin-url: "https://s3.amazonaws.com/int-wutsi"
    endpoint-url: "https://ik.imagekit.io/cx8qxsgz4d"

  oauth:
    github:
      client-id: "2430c202b7d87c5eddce"
      client-secret: "cf900a9f2c73012795ea95a4ecf16be80555659e"
      callback-url: ${wutsi.base-url}/login/github/callback
    facebook:
      client-id: "00000000"
      client-secret: "00000000"
      callback-url: "${wutsi.base-url}/login/facebook/callback"
      scope: "public_profile"
    google:
      client-id: "00000000"
      client-secret: "00000000"
      callback-url: "${wutsi.base-url}/login/google/callback"
      scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
    twitter:
      client-id: "0000000"
      client-secret: "0000000000"
      callback-url: "${wutsi.base-url}/login/twitter/callback"

  pwa:
    manifest:
      name: "Wutsi"
    firebase:
      project-id: "wutsi-int-274521"
      api-key: "AIzaSyD5-Sf-lZTyJpMXcZS6DPb1LNJN9tnmIMA"
      app-id: "1:255903690741:web:87ac16910084876e07fabc"
      public-vapid-key: "BFmAST-JbJbs_viT2GQQ2iS36HSioZ2B-Q0xgETvjKJyBGVZdfE2DqO9VmWycDe5JEYQ3tDaGuqz_fA0PN_4ZPs"
      sender-id: "255903690741"

  storage:
    local:
      directory: "${user.home}/wutsi/upload"
    servlet:
      path: "/storage"
      hostname: "localhost:${server.port}"
      url: "http://${wutsi.storage.servlet.hostname}${wutsi.storage.servlet.path}"
    s3:
      bucket:

  toggles:
    announcement: true              # Enable announcenement
    channel: true                   # Enable publication channels
    channel-twitter: true           # Enable Twitter Channel
    channel-facebook: true          # Enable Facebook Channel
    comment: true                   # Enable Comments
    earning: true                   # Show Earnings
    google-one-tap-sign-in: false   # Integration of Google One Tag signin - https://developers.google.com/identity/one-tap/web
    pwa: true                       # PWA
    pwa-push-notification: true     # Enable PWA Push Notification?
    recommendation: true            # Show articles recommendations in reader
    share-button: false             # Show single share button, instead of individual social share buttons
    image-kit: true                 # Integration with imagekit.io
    sso-facebook: false             # SSO Login with social network sites
    sso-google: false
    sso-twitter: false
    sso-github: true
    qa-login: false
    wpp: true                       # Wutsi Partner Program
