wutsi:
  asset-url: https://int-wutsi.s3.amazonaws.com/static/wutsi-blog-web
  base-url: https://www.wutsi.com

  backend:
    baseurl: https://com-wutsi-blog.herokuapp.com

  oauth:
      facebook:
        client-id: 466330503408293

  toggles:
    sso-facebook: true
    sso-google: false
    sso-twitter: false
    sso-github: false
    qa-login: false
