wutsi:
  base-url: "https://wutsi.com"
  backend:
    baseurl: https://com-wutsi-blog.herokuapp.com


  toggles:
    sso-facebook: true
    sso-google: true
    sso-twitter: false
    sso-github: false
    qa-login: false
