wutsi:
  backend:
    baseurl: https://int-com-wutsi-blog.herokuapp.com

  oauth:
      github:
        client-id: 43bf80531cd351c84f5b
        client-secret: 986634ef3a7c8ac6e66f9a75f5b0a1c4dec68918
      facebook:
        client-id: 629340480740249
        client-secret: d8549ed13e6217a3c65e2c5ce69283fa

  storage:
    s3:
      region: "us-east-1"
      bucket: "int-wutsi-blog"
    servlet:
      hostname: "int-com-wutsi-blog.herokuapp.com"

  toggles:
    sso-facebook: true
    sso-google: false
    sso-twitter: true
    sso-github: true
