spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

  security:
    basic:
      enabled: false

  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 10240KB

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
    min-response-size: 512

logging:
  level:
    root: INFO
    com.wutsi: DEBUG
    org.springframework: INFO

  pattern:
    console: "%d Type=%level Logger=%c Thread=%thread %m%n"
    file: "%d Type=%level Logger=%c Thread=%thread %m%n"

wutsi:
  asset-url: ""
  domain: localhost
  base-url: "http://${wutsi.domain}:8081"

  aws:
    s3:
      region: "us-east-1"

  backend:
    base-url: http://localhost:8080
    authentication:
      endpoint: ${wutsi.backend.base-url}/v1/auth
    story:
      endpoint: ${wutsi.backend.base-url}/v1/story
    tag:
      endpoint: ${wutsi.backend.base-url}/v1/tag
    track:
      endpoint: ${wutsi.backend.base-url}/v1/track
    user:
      endpoint: ${wutsi.backend.base-url}/v1/user

  http:
    client-id: wutsi-blog-web

  oauth:
    github:
      client-id: 2430c202b7d87c5eddce
      client-secret: cf900a9f2c73012795ea95a4ecf16be80555659e
      callback-url: ${wutsi.base-url}/login/github/callback
    facebook:
      client-id: 00000000
      client-secret: 0000000000000000
      callback-url: ${wutsi.base-url}/login/facebook/callback
    google:
      client-id: 00000000
      client-secret: 0000000000000000
      callback-url: ${wutsi.base-url}/login/google/callback
    twitter:
      client-id: "WWFN2AU1eCQFmY9vzMgv6sCmX"
      client-secret: "vKWfai4Ms8p3C5CliphAK6ShGrACOqRtxo6KqaAccrOnPI6paN"
      callback-url: ${wutsi.base-url}/login/twitter/callback

  storage:
    local:
      directory: "${user.home}/wutsi/upload"
    servlet:
      path: "/storage"
      hostname: "localhost:${server.port}"
      url: "http://${wutsi.storage.servlet.hostname}${wutsi.storage.servlet.path}"
    s3:
      bucket:

  google:
    ga:
      code:

  toggles:
    sso-facebook: false
    sso-google: false
    sso-twitter: false
    sso-github: true
    qa-login: false
