spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  security:
    basic:
      enabled: false
    oauth2:
      client:
        registration:
          github:
            client-id: 2430c202b7d87c5eddce
            client-secret: cf900a9f2c73012795ea95a4ecf16be80555659e
          facebook:
            client-id: 00000000
            client-secret: 0000000000000000
#          twitter:
#            provider: "oauth2"
#            client-id: "WWFN2AU1eCQFmY9vzMgv6sCmX"
#            client-secret: "vKWfai4Ms8p3C5CliphAK6ShGrACOqRtxo6KqaAccrOnPI6paN"

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
    min-response-size: 512

logging:
  level:
    root: INFO
    com.wutsi: DEBUG
    org.springframework: INFO

  pattern:
    console: "%d Type=%level Logger=%c Thread=%thread %m%n"
    file: "%d Type=%level Logger=%c Thread=%thread %m%n"

wutsi:
  backend:
    baseurl: http://localhost:8080
    authentication:
      endpoint: ${wutsi.backend.baseurl}/v1/auth
    story:
      endpoint: ${wutsi.backend.baseurl}/v1/story
    tag:
      endpoint: ${wutsi.backend.baseurl}/v1/tag
    user:
      endpoint: ${wutsi.backend.baseurl}/v1/user
  http:
    client-id: wutsi-blog-app
  toggles:
    sso-facebook: false
    sso-google: false
    sso-twitter: false
    sso-github: true
