wutsi:
  asset-url: https://${wutsi.storage.s3.bucket}.s3.amazonaws.com/static/wutsi-blog-web
  domain: www.wutsi.com
  base-url: https://${wutsi.domain}

  backend:
    baseurl: https://com-wutsi-blog.herokuapp.com


  image-kit:   # Configuration of integration with imagekit.io
    origin-url: "https://s3.amazonaws.com/prod-wutsi"
    endpoint-url: "https://ik.imagekit.io/toifevuwjn"

  oauth:
      facebook:
        client-id: "466330503408293"
      github:
        client-id: "900cfd0accedc133ea5b"
      google:
        client-id: "28035834807-789vmmloq8u12nvvp4ki2bbcqsqvskf0.apps.googleusercontent.com"
      twitter:
        client-id: "WWFN2AU1eCQFmY9vzMgv6sCmX"

  pwa:
    firebase:
      server-key: "AAAABocQ47c:APA91bGCAAEFCibq-Apvjc_7_rzyWdeymOoh-A_3-9qBQ93Q0q5YvnLLUFrHVxXvDF6P_umcOScEEQLVuYifmZVyUaR3GeRGzJGD8los54kwTmXLrUsUmHUGi9qg0z8pL6n_8Ye5-YtT"
      sender-id: "28035834807"

  toggles:
    channel: true
    channel-twitter: true
    channel-facebook: false
    earning: true
    google-one-tap-sign-in: true
    imagekit: true
    pwa: true
    pwa-push-notification: true
    recommendation: true
    share-button: false
    publish: true
    sso-facebook: true
    sso-google: true
    sso-github: false
    sso-twitter: false
    wpp: true

  google:
    ga:
      code: "UA-120456146-1"

  facebook:
    pixel:
      code: "553466401984152"

  storage:
    s3:
      bucket: "prod-wutsi"
