name: sync-s3

on:
  push:
    branches:
      - master

jobs:
  sync-s3:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #      - name: S3-Deploy-Test
      #        env:
      #          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      #          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      #        run: |
      #          aws s3 sync \
      #            --acl public-read \
      #            --region us-east-1 \
      #            target/classes/public/ s3://prod-wutsi/static/wutsi-blog-web

      - name: S3-Deploy-Prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws s3 sync \
            --acl public-read \
            --region us-east-1 \
            target/classes/public/ s3://prod-wutsi/static/wutsi-blog-web

